name: watch-dogs
on:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  watch-dogs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Run
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        run: make run
